# Generated by Django 5.1.6 on 2025-03-08 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_genders_alter_students_options_students_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.genders'),
        ),
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.CharField(max_length=255, null=True, verbose_name='Фото'),
        ),
    ]
