# Generated by Django 5.1.6 on 2025-03-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_students_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.CharField(max_length=255, null=True, verbose_name='Фото'),
        ),
    ]
