# Generated by Django 5.1.6 on 2025-03-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_students_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
    ]
