# Generated by Django 5.1.6 on 2025-03-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_students_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='lastname',
            field=models.CharField(default='-', max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.CharField(default='-', max_length=255, null=True, verbose_name='Фото'),
        ),
    ]
