# Generated by Django 5.1.6 on 2025-03-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='specialities',
            options={'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
    ]
