# Generated by Django 5.1.6 on 2025-03-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_groups_options_alter_specialities_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='count_of_students',
            field=models.IntegerField(null=True, verbose_name='Количесвто студентов'),
        ),
    ]
